/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\progammer.glb --transform 
Files: .\progammer.glb [6.42MB] > C:\Users\Drevv\Desktop\portfolio-nam\public\models\progammer-transformed.glb [667.11KB] (90%)
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-f844c0357d284fd8baa1435e9ff31bb2
Title: Retro computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Progammer(props) {
  const { nodes, materials } = useGLTF('models/progammer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Part2} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Part1} />
    </group>
  )
}

useGLTF.preload('models/progammer-transformed.glb')
